import Header from "@/components/Header/Header";
import { Metadata } from "next";
import "../../src/style.css";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Learning NextJS - coding",
    template: "%s | coding",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
